version: "3.7"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: metanginx
    volumes:
      - nginxlog-volume:/var/log/nginx
    ports:
      - "80:80"
    expose:
      - "80"
    depends_on: 
      - server
  server:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server
    container_name: metaserver
    volumes:
      - logs-volume:/app/logs
    depends_on: 
      - db
  db:
    image: mysql:8.0.21
    restart: always
    ports: 
      - "3306"
    container_name: metadb
    environment: 
      # MYSQL 패스워드 설정 옵션
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: metabus
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
  logs-volume:
  nginxlog-volume:

